# Generated by Django 3.2.15 on 2022-10-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_genres_ratings_series_statuses_subgenres'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='series',
            table='series',
        ),
    ]
