# Generated by Django 3.2.15 on 2022-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_carts_cartsbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('p_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'order_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('p_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
