# Generated by Django 3.2.15 on 2022-12-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0008_auto_20221202_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
